Module3 task1
htmlacademy-react/1332021-guess-melody-5 pull request #4
Opened 2020-10-06 15:48 UTC by vadimkozin

2020-10-07 07:08 UTC, abeluzhenko requested changes

2020-10-07 07:08 UTC, abeluzhenko commented on src/types/types.js
> +export const appType = {
Эти объекты теперь экспортируемые константы, и по [критериям](https://up.htmlacademy.ru/react/5/criteries#b6) нам нужно их именовать в pascal case

2020-10-07 07:08 UTC, abeluzhenko commented on src/types/types.js
> +    type: oneOf([GameType.ARTIST, GameType.GENRE]).isRequired,
Можно также это значение для `type` вынести в отдельную константу (например, `QUESTION_TYPE`), чтобы не дубировать код.

2020-10-07 08:01 UTC, vadimkozin commented on src/types/types.js
> +export const appType = {
Перевёл в pascal case.  Только не совсем  мне понятно. Если экспортируемые константы, то тогда вместо appType нужно что-то типа APP_TYPE.  Если pascalcase, то AppType.   В pascalcase по критериям мы должны называть перечисления, но типы, что я описываю в src/types/types.js как-то не очень похожи на перечисления, поэтому и называл эти объекты в стиле camelcase как appType, welcomeType и тд.    И в критерии Б6, куда ведёт твоя ссылка, что  выше, написано только про константы (UPPER_SNAKE_CASE) .  Как-же эти объекты наименовать правильно: appType, APP_TYPE, AppType?

2020-10-07 17:51 UTC, abeluzhenko commented on src/types/types.js
> +export const appType = {
Прошу прощения, это я перепутал. Конечно же UPPER_CASE, не Pascal.

2020-10-07 17:54 UTC, abeluzhenko approved these changes

2020-10-07 18:07 UTC, vadimkozin commented on src/types/types.js
> +export const appType = {
Перевёл в UPPER_SNAKE_CASE

2020-10-08 09:52 UTC, abeluzhenko approved these changes

2020-10-08 09:52 UTC, merged