Module5 task1
htmlacademy-react/1332021-guess-melody-5 pull request #7
Opened 2020-10-20 11:53 UTC by vadimkozin

2020-10-22 08:06 UTC, abeluzhenko requested changes

2020-10-22 08:06 UTC, abeluzhenko commented on src/components/game-screen/game-screen.jsx
> +        </GenreQuestionScreenWrapped>
Здесь можно было бы сразу получить нужный враппер и использовать в jsx уже его:
```
const Wrapper = question.type === GameType.ARTIST 
  ? ArtistQuestionScreenWrapped 
  : GenreQuestionScreenWrapped;
```
И использовать так: 
```
<Wrapper question={question} onAnswer={onUserAnswer}>
  <Mistakes count={mistakes}/>
</Wrapper>
```

2020-10-22 15:20 UTC, vadimkozin commented on src/store/action.js
> +    }
( Поразмышляю немного). Не стал здесь делать мапу. Вариантов всего 2 и switch выглядит хорошо. Если-бы вариантов было >=3, то тогда да. Да и если вдруг появиться case с параметрами отличными от (question, userAnswer), то  тогда опять нужно будет переделывать на switch.

2020-10-23 06:38 UTC, abeluzhenko commented on src/store/action.js
> +    }
Код корректный и критериев не нарушает. Но моя работа - делиться опытом и я делюсь)

Согласен, что мапа для 2 вариантов это наверное черезчур. Но не могу согласиться с твоими выводам. Имхо, это нарушение принципа YAGNI, ты пытаешься учесть возможные будущие изменения и это ведет к переусложненному дизайну.
Если ранжировать варианты по простоте то получится так:
1. If ...esle или лучше тернарник `const getIsAnswerCorrect = A ? B : C`
2. Мапа
3. Switch ...case

В данном случае, имхо, switch не нужен, т.к. не используются его основные фичи: default-case и обработка нескольких case в одном действии. 
А мапа и условник имеют более узкий интерфейс, что хорошо. На входе и на выходе данные в определенном формате, никакой истории, никаких побочных эффектов, легко читать, легко тестировать (если выделить в отдельную функцию).

2020-10-23 06:41 UTC, abeluzhenko approved these changes

2020-10-23 06:41 UTC, merged

2020-10-24 11:52 UTC, vadimkozin commented on src/store/action.js
> +    }
Спасибо за детальный разбор и за то что делишься опытом. Направил меня в нужное русло.  Получается здесь тернарник самое то.